(clojure.lang.RT/loadLibrary "react_render")
(react_render/initialize  "../bundle.js")
(println "Result of evaluating:" (react_render/render_path "/"))
(println "Result of evaluating:" (react_render/render_path "/abc"))
(println "Result of evaluating:" (react_render/render_path "/red"))
(println "Result of evaluating:" (react_render/render_path "/blue"))
